# Generated by Django 3.0.8 on 2020-11-04 18:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.CharField(max_length=255, verbose_name='telefone')),
                ('data_nascimento', models.DateField(max_length=255, verbose_name='Data de Nascimento')),
                ('documento', models.CharField(max_length=255, verbose_name='Documento')),
                ('documento_tipo', models.CharField(max_length=255, verbose_name='Tipo Documento')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF')),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=255, verbose_name='Número')),
                ('estado', models.CharField(max_length=255)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ramal', models.CharField(max_length=255, null=True, verbose_name='Ramal')),
                ('contato_de_emergencia_nome', models.CharField(max_length=255, null=True, verbose_name='Nome')),
                ('contato_de_emergencia_telefone', models.CharField(max_length=255, null=True, verbose_name='Telefone')),
                ('contato_de_emergencia_parentesco', models.CharField(max_length=255, null=True, verbose_name='Parentesco')),
                ('nacionalidade', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=255, null=True)),
                ('area_formacao', models.CharField(max_length=255, verbose_name='Área de Formação')),
                ('empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa Terceirizada')),
                ('registro_inpe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Matrícula SIAPE')),
                ('estado_civil', models.CharField(blank=True, max_length=255, null=True)),
                ('externo', models.BooleanField(default=False, verbose_name='Usuário Externo')),
                ('uid', models.IntegerField(default=0, verbose_name='UID')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['username'],
                'permissions': (('responsavel_colaborador', 'Responsável pode aprovar acesso colaborador'), ('secretaria_colaborador', 'Secretaria pode revisar colaborador'), ('suporte_colaborador', 'Suporte pode criar o colaborador'), ('chefia_colaborador', 'Chefia por aprovar colaborador')),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=255, verbose_name='vinculo')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'ordering': ['vinculo'],
            },
        ),
    ]
