# Generated by Django 3.0.8 on 2021-02-17 18:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('colaborador', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Divisao', verbose_name='Divisão'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='predio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Predio', verbose_name='Prédio'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaborador.Vinculo', verbose_name='vínculo'),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('colaborador.colaborador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
