# Generated by Django 3.2.1 on 2021-05-07 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.divisao', verbose_name='Divisão | Coordenação'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='predio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.predio', verbose_name='Prédio'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_user', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaborador.vinculo', verbose_name='vínculo'),
        ),
    ]
