# Generated by Django 3.0.8 on 2020-10-26 20:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Divisao', verbose_name='Divisão'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='predio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Predio', verbose_name='Prédio'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsavel_user', to='colaborador.Colaborador', verbose_name='Responsavel'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colaborador.Vinculo', verbose_name='vínculo'),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('colaborador.colaborador',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
