# Generated by Django 3.0.8 on 2021-03-03 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_auto_20210227_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(max_length=255, verbose_name='Recurso a ser acessado')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('data_abertura', models.DateTimeField(blank=True, null=True, verbose_name='Data da Abertura')),
                ('data_validade', models.DateTimeField(blank=True, null=True, verbose_name='Data Validade')),
                ('mac_cabeado', models.CharField(max_length=255, verbose_name='MAC Address Cabeado')),
                ('mac_wifi', models.CharField(max_length=255, verbose_name='MAC Address Wireless')),
                ('justificativa', models.CharField(max_length=255, verbose_name='Justificativa')),
                ('documento', models.CharField(max_length=255, verbose_name='Documento referência')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'VPN',
                'verbose_name_plural': 'VPNs',
                'ordering': ['-data_validade'],
            },
        ),
    ]
