# Generated by Django 3.2 on 2021-04-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_grupoacesso_data'),
        ('colaborador', '0002_auto_20210407_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de trabalho'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.divisao', verbose_name='Divisão | Coordenação'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
