# Generated by Django 3.0.8 on 2021-03-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_auto_20210303_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='area_formacao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='sexo',
        ),
    ]
