# Generated by Django 3.0.8 on 2021-03-23 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_auto_20210319_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpn',
            name='documento',
        ),
    ]
