# Generated by Django 3.0.8 on 2021-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0004_remove_vpn_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='mac_cabeado',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC Address Cabeado'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='mac_wifi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MAC Address Wireless'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Status'),
        ),
    ]
