# Generated by Django 3.0.8 on 2021-03-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_auto_20210323_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpn',
            name='data_abertura',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Abertura'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data da solicitação'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data Validade'),
        ),
        migrations.AlterField(
            model_name='vpn',
            name='status',
            field=models.CharField(blank=True, default='Solicitada', max_length=255, null=True, verbose_name='Status'),
        ),
    ]
