# Generated by Django 3.2 on 2021-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NagiosServicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255, verbose_name='serviço')),
                ('comando', models.CharField(max_length=255, verbose_name='comando Nagios')),
                ('tempo', models.IntegerField(verbose_name='Tempo de verificação')),
                ('padrao', models.BooleanField(default=False, verbose_name='Ativar por padrão')),
            ],
            options={
                'verbose_name': 'Nagios Serviço',
                'verbose_name_plural': 'Nagios Serviços',
                'ordering': ('servico',),
            },
        ),
    ]
