# Generated by Django 3.2 on 2021-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_nagiosservicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagiosservicos',
            name='servico',
            field=models.CharField(max_length=255, verbose_name='Serviço'),
        ),
    ]
