# Generated by Django 3.2 on 2021-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_alter_nagiosservicos_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prometheus',
            name='jobname',
            field=models.CharField(max_length=255, verbose_name='jobname'),
        ),
        migrations.AlterField(
            model_name='prometheus',
            name='porta',
            field=models.IntegerField(verbose_name='porta'),
        ),
    ]
