# Generated by Django 3.2.1 on 2021-05-07 13:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisao', models.CharField(max_length=255, verbose_name='Divisão|Coordenação')),
                ('divisao_completo', models.CharField(max_length=255, null=True, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('coordenacao', models.CharField(max_length=255, null=True, verbose_name='Coordenação')),
                ('chefe_ativo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ativo')),
                ('chefe_substituto_ativo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ativo')),
                ('chefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chefe_user', to=settings.AUTH_USER_MODEL, verbose_name='Chefe')),
                ('chefe_substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chefe_user_2', to=settings.AUTH_USER_MODEL, verbose_name='Chefe Substituto')),
            ],
            options={
                'verbose_name': 'Divisão | Coordenação',
                'verbose_name_plural': 'Divisões | Coordenações',
                'ordering': ['divisao'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=255, verbose_name='Grupo')),
                ('grupo_sistema', models.CharField(max_length=255, unique=True, verbose_name='Grupo no sistema')),
                ('gid', models.IntegerField(default=0)),
                ('share', models.BooleanField(blank=True, default=False, null=True, verbose_name='Share')),
                ('operacional', models.BooleanField(blank=True, default=False, null=True, verbose_name='Operacional')),
                ('desenvolvimento', models.BooleanField(blank=True, default=False, null=True, verbose_name='Desenvolvimento')),
                ('pesquisa', models.BooleanField(blank=True, default=False, null=True, verbose_name='Pesquisa')),
                ('documento', models.BooleanField(blank=True, default=False, null=True, verbose_name='Documento')),
                ('data_criado', models.DateField(null=True, verbose_name='Data de Criação')),
                ('confirmacao', models.BooleanField(default=False, null=True, verbose_name='Confirmação de Assinatura')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.divisao', verbose_name='Divisão|Coordenação')),
            ],
            options={
                'verbose_name': 'Grupo de Trabalho',
                'verbose_name_plural': 'Grupos de Trabalho',
                'ordering': ['divisao', 'grupo'],
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.CharField(max_length=255, null=True, verbose_name='Prédio')),
                ('predio_sistema', models.CharField(max_length=255, null=True, unique=True, verbose_name='Abreviação')),
                ('linhas', models.IntegerField(default=0)),
                ('colunas', models.IntegerField(default=0)),
                ('sensores', models.IntegerField(default=0, help_text='Número de sensores no datacenter')),
                ('areas', models.CharField(blank=True, help_text='Conjunto de areas neutras no mapa: (1, 36, 1, 19)/(36, 43, 1, 4)/(43, 46, 1, 30)', max_length=255, null=True, verbose_name='Areas neutras')),
            ],
            options={
                'verbose_name': 'Prédio',
                'verbose_name_plural': 'Prédios',
                'ordering': ['predio'],
            },
        ),
        migrations.CreateModel(
            name='GrupoPortal',
            fields=[
            ],
            options={
                'verbose_name': 'Grupo no Portal',
                'verbose_name_plural': 'Grupos no Portal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelGrupoTrabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupotrabalho')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['responsavel'],
            },
        ),
        migrations.AddField(
            model_name='grupotrabalho',
            name='responsavel',
            field=models.ManyToManyField(through='core.ResponsavelGrupoTrabalho', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.CreateModel(
            name='GrupoAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_acesso', models.CharField(max_length=255, verbose_name='Regra de Acesso')),
                ('hbac_freeipa', models.CharField(max_length=255, verbose_name='HBAC no FreeIPA')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('grupo_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupotrabalho')),
            ],
            options={
                'verbose_name': 'Grupo de Acesso',
                'verbose_name_plural': 'Grupos de Acesso',
                'ordering': ['grupo_trabalho', 'grupo_acesso'],
            },
        ),
        migrations.CreateModel(
            name='ColaboradorGrupoAcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovacao', models.IntegerField(default=0, verbose_name='status')),
                ('atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo_acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupoacesso')),
            ],
            options={
                'verbose_name': 'Grupo de Acesso',
                'verbose_name_plural': 'Grupos de Acesso',
                'ordering': ['grupo_acesso'],
            },
        ),
    ]
