# Generated by Django 3.2 on 2021-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoacesso',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
