# Generated by Django 3.2 on 2021-06-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_nagiosservicos'),
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='ServidorNagiosServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nagios_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoramento.nagiosservicos')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.servidor')),
            ],
        ),
        migrations.AddField(
            model_name='servidor',
            name='nagios_servicos',
            field=models.ManyToManyField(blank=True, through='infra.ServidorNagiosServico', to='monitoramento.NagiosServicos'),
        ),
    ]
