# Generated by Django 3.0.8 on 2021-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='ldap',
            field=models.IntegerField(default=0, verbose_name='ldap'),
        ),
    ]
