# Generated by Django 3.2 on 2021-06-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noc', '0003_auto_20210610_1737'),
        ('infra', '0002_auto_20210610_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencia_checklist', to='noc.checklist'),
        ),
    ]
