# Generated by Django 3.0.8 on 2021-03-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_auto_20210316_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateHostnameIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostnameip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infra.HostnameIP', verbose_name='Hostname')),
            ],
            options={
                'verbose_name': 'Hostname',
                'verbose_name_plural': 'Hostnames',
            },
        ),
        migrations.AddField(
            model_name='servidor',
            name='vm_remover',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Remover VM'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome'),
        ),
        migrations.CreateModel(
            name='TemplateVM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome')),
                ('configuracao', models.CharField(max_length=255, verbose_name='Configuração')),
                ('comando_antes', models.TextField(blank=True, null=True, verbose_name='Configuração Antes do Reboot')),
                ('comando_depois', models.TextField(blank=True, null=True, verbose_name='Configuração Depois do  Reboot')),
                ('ambiente_virtual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_ambiente_virtual', to='infra.AmbienteVirtual', verbose_name='Ambiente Virtual')),
                ('origens', models.ManyToManyField(through='infra.TemplateHostnameIP', to='infra.HostnameIP')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='templatehostnameip',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.TemplateVM'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='vm_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidor_template', to='infra.TemplateVM', verbose_name='Template'),
        ),
        migrations.AlterUniqueTogether(
            name='templatehostnameip',
            unique_together={('hostnameip',)},
        ),
    ]
