# Generated by Django 3.2 on 2021-06-11 13:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_ocorrencia_checklist'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equipamentoparte',
            managers=[
                ('objetcs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(default='Manutenção', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(blank=True, default='Analisando', max_length=255, null=True, verbose_name='status'),
        ),
    ]
