# Generated by Django 3.0.8 on 2021-03-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_auto_20210323_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatevm',
            name='comando_IP',
            field=models.TextField(blank=True, null=True, verbose_name='Configuração para troca do IP'),
        ),
    ]
