# Generated by Django 3.0.8 on 2021-03-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_templatevm_comando_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateComando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(help_text='{template_origem_ip}: IP da VM de origem do template,                    {vm_ip}: IP da VM nova,                    {template_origem}: Hostname da VM de origem do template,                    {vm}: Hostname da VM nova,                     {server_freeipa}: Hostname da VM nova', max_length=255)),
                ('configuracao', models.CharField(max_length=255, verbose_name='Configuração')),
            ],
        ),
        migrations.AddField(
            model_name='templatevm',
            name='comandos',
            field=models.ManyToManyField(to='infra.TemplateComando'),
        ),
    ]
