# Generated by Django 3.2 on 2021-06-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_rede_monitorado'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='equipamentoparte',
            managers=[
            ],
        ),
    ]
