# Generated by Django 3.0.8 on 2021-03-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_auto_20210326_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatevm',
            name='comandos',
        ),
        migrations.AddField(
            model_name='templatecomando',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_comando_template', to='infra.TemplateVM'),
        ),
    ]
