# Generated by Django 3.2 on 2021-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_alter_equipamentoparte_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='grupos',
            field=models.CharField(max_length=255, null=True, verbose_name='grupos'),
        ),
    ]
