# Generated by Django 3.0.8 on 2021-03-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0007_auto_20210326_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatevm',
            name='comando_IP',
        ),
        migrations.RemoveField(
            model_name='templatevm',
            name='comando_antes',
        ),
        migrations.RemoveField(
            model_name='templatevm',
            name='comando_depois',
        ),
        migrations.AlterField(
            model_name='templatecomando',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_comandos', to='infra.TemplateVM'),
        ),
    ]
