# Generated by Django 3.0.8 on 2021-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0008_auto_20210326_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecomando',
            options={'ordering': ['configuracao', 'priodade'], 'verbose_name': 'Comando', 'verbose_name_plural': 'Comandos'},
        ),
        migrations.AddField(
            model_name='templatecomando',
            name='priodade',
            field=models.IntegerField(null=True),
        ),
    ]
