# Generated by Django 3.0.8 on 2021-03-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0009_auto_20210326_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatecomando',
            options={'ordering': ['configuracao', 'prioridade'], 'verbose_name': 'Comando', 'verbose_name_plural': 'Comandos'},
        ),
        migrations.RenameField(
            model_name='templatecomando',
            old_name='priodade',
            new_name='prioridade',
        ),
    ]
