# Generated by Django 3.0.8 on 2021-03-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0010_auto_20210326_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rede',
            options={'ordering': ['rede']},
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='ldap',
        ),
        migrations.AddField(
            model_name='servidor',
            name='conta',
            field=models.CharField(default='Aguardando', max_length=255, verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='templatecomando',
            name='comando',
            field=models.CharField(help_text=' Variáveis dos comandos\n                    {template_origem_ip}: IP da VM de origem do template\n                    {vm_ip}: IP da VM nova\n                    {template_origem}: Hostname da VM de origem do template\n                    {vm}: Hostname da VM nova \n                    {server_freeipa}: Servidor do Freeipa \n                    {admin_freeipa}: Usuário admin do Freeipa \n                    {password_freeipa}: Password do admin do Freeipa', max_length=255),
        ),
    ]
