# Generated by Django 3.0.8 on 2020-11-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0002_auto_20201104_1854'),
        ('infra', '0002_auto_20201119_1845'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=255)),
                ('sla', models.IntegerField(default=30, help_text='Acordo de Nível de Serviço. Mensura o nível de entrega de serviços que um contratante ou cliente, em horas', verbose_name='SLA')),
                ('grupo_portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GrupoPortal', verbose_name='Fila de Atendimento')),
            ],
            options={
                'ordering': ['grupo_portal'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket', models.AutoField(primary_key=True, serialize=False, verbose_name='Número do Ticket')),
                ('status', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em Atendimento'), (3, 'Fechado'), (4, 'Cancelado')], default=1, verbose_name='Status')),
                ('prioridade', models.IntegerField(blank=2, choices=[(3, 'Alta'), (2, 'Normal'), (1, 'Baixa')], default=2, verbose_name='Prioridade')),
                ('origem', models.IntegerField(choices=[(1, 'Monitoramento'), (2, 'Atendimento')], verbose_name='origem')),
                ('primeiro_atendimento', models.CharField(blank=True, help_text='Número da OS externa', max_length=255, verbose_name='Primeiro Atendimento')),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaborador.Colaborador')),
                ('equipamento', models.ManyToManyField(to='infra.Equipamento')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to='colaborador.Colaborador')),
                ('problema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='desk.Problema')),
            ],
            options={
                'ordering': ['-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='TicketAtualizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateTimeField(verbose_name='Atualização')),
                ('status', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Em Atendimento'), (2, 'Assentamento'), (3, 'Aguardando agente externo'), (4, 'Em estudo'), (5, 'Fechado'), (6, 'Cancelado')], default=1, verbose_name='Status')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colaborador.Colaborador')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Ticket')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
