# Generated by Django 3.2 on 2021-05-03 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=255)),
                ('upload', models.FileField(upload_to='documento/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('grupo', models.ManyToManyField(blank=True, to='auth.Group')),
            ],
            options={
                'ordering': ['modificado', 'documento'],
            },
        ),
    ]
