# Generated by Django 3.2 on 2021-06-11 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noc', '0003_auto_20210610_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='checklist',
            name='outros',
            field=models.TextField(blank=True, null=True, verbose_name='Geral'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='responsaveis',
            field=models.ManyToManyField(through='noc.ChecklistResponsaveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
